service: think-in-api
# app and org for use with dashboard.serverless.com
app: think-in-api
org: crisanmm

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  memorySize: 128
  timeout: 5

functions:
  post-avatar:
    handler: avatars/post-avatar.postAvatar
    events:
      - http:
          path: /avatars
          method: post
          cors: true
  # hello:
  #   handler: handler.hello
  #   events:
  #     - http:
  #         path: /
  #         method: get
  #         cors: true
  # resize-image:
  # handler: resize-image/index.resizeImage

plugins:
  - serverless-plugin-typescript
