version: 0.0
os: linux
files:
  - source: /
  - destination: ~/websocket-server
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      runas: root
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root