version: 0.0
os: linux
files:
  - source: /
    destination: ~/websocket-server/
hooks:
  ApplicationStop:
    - location: ./scripts/application-stop.sh
  BeforeInstall:
    - location: ./scripts/before-install.sh
  ApplicationStart:
    - location: ./scripts/application-start.sh