version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - apt --assume-yes update
      - apt --assume-yes install npm
    finally:
      - echo Install phase done.
  pre_build:
    commands:
      - cd app/BE/stage_server
      - npm ci
    finally:
      - echo Prebuild phase done.
  build:
    commands:
      - npm run build
    finally:
      - echo Build phase done.
artifacts:
  base-directory: 'app/BE/stage_server'
  files:
    - 'out/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'appspec.yml'
    - 'scripts/**/*'
    - './env'
